"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.clearRoomCanvas = exports.updateCanvasShape = exports.deleteCanvasShape = exports.getCanvasShape = exports.createCanvas = exports.getRoomCanvas = exports.deleteUserCanvasInRoom = exports.getRoomByRoomId = exports.getRoomIfExists = exports.connectUserWithRoom = exports.getRoomWithUsers = exports.getRoomWithUsersById = exports.removeUserFromRoom = exports.deleteRoom = exports.getRoomsByUserId = exports.getRoomByName = exports.createRoom = exports.getUserById = exports.createUser = exports.getUserByEmail = void 0;
const userService_1 = require("./src/services/userService");
Object.defineProperty(exports, "getUserByEmail", { enumerable: true, get: function () { return userService_1.getUserByEmail; } });
Object.defineProperty(exports, "createUser", { enumerable: true, get: function () { return userService_1.createUser; } });
Object.defineProperty(exports, "getUserById", { enumerable: true, get: function () { return userService_1.getUserById; } });
const roomService_1 = require("./src/services/roomService");
Object.defineProperty(exports, "createRoom", { enumerable: true, get: function () { return roomService_1.createRoom; } });
Object.defineProperty(exports, "getRoomByName", { enumerable: true, get: function () { return roomService_1.getRoomByName; } });
Object.defineProperty(exports, "getRoomsByUserId", { enumerable: true, get: function () { return roomService_1.getRoomsByUserId; } });
Object.defineProperty(exports, "getRoomWithUsersById", { enumerable: true, get: function () { return roomService_1.getRoomWithUsersById; } });
Object.defineProperty(exports, "deleteRoom", { enumerable: true, get: function () { return roomService_1.deleteRoom; } });
Object.defineProperty(exports, "removeUserFromRoom", { enumerable: true, get: function () { return roomService_1.removeUserFromRoom; } });
Object.defineProperty(exports, "getRoomWithUsers", { enumerable: true, get: function () { return roomService_1.getRoomWithUsers; } });
Object.defineProperty(exports, "connectUserWithRoom", { enumerable: true, get: function () { return roomService_1.connectUserWithRoom; } });
Object.defineProperty(exports, "getRoomIfExists", { enumerable: true, get: function () { return roomService_1.getRoomIfExists; } });
Object.defineProperty(exports, "getRoomByRoomId", { enumerable: true, get: function () { return roomService_1.getRoomByRoomId; } });
const canvasService_1 = require("./src/services/canvasService");
Object.defineProperty(exports, "createCanvas", { enumerable: true, get: function () { return canvasService_1.createCanvas; } });
Object.defineProperty(exports, "deleteUserCanvasInRoom", { enumerable: true, get: function () { return canvasService_1.deleteUserCanvasInRoom; } });
Object.defineProperty(exports, "getRoomCanvas", { enumerable: true, get: function () { return canvasService_1.getRoomCanvas; } });
Object.defineProperty(exports, "getCanvasShape", { enumerable: true, get: function () { return canvasService_1.getCanvasShape; } });
Object.defineProperty(exports, "deleteCanvasShape", { enumerable: true, get: function () { return canvasService_1.deleteCanvasShape; } });
Object.defineProperty(exports, "updateCanvasShape", { enumerable: true, get: function () { return canvasService_1.updateCanvasShape; } });
Object.defineProperty(exports, "clearRoomCanvas", { enumerable: true, get: function () { return canvasService_1.clearRoomCanvas; } });
